const numberGuess = document.getElementsByClassName('numbers');
const guessOne = document.getElementById('firstN');
const guessTwo = document.getElementById('secondN');
const guessThree = document.getElementById('thirdN');
const submit = document.getElementById('submit')
const rowOneNumberOne = document.getElementById('firstResult');
const rowOneNumberTwo = document.getElementById('secondResult');
const rowOneNumberThree = document.getElementById('thirdResult');



const numbers = [0,1,2,3,4,5,6,7,8,9];
const correctPlace = " correct and in the right spot. ";
const incorrectPlace = " correct but in the wrong spot.";
const wrong = "All incorrect!";

rowOneNumberOne.textContent = 6;
rowOneNumberTwo.textContent = 0;
rowOneNumberThree.textContent = 9;

function getGuess(one, two, three) {
    one = guessOne.textContent;
    two = guessTwo.textContent;
    three = guessThree.textContent;
}

submit.addEventListener('click', function(){
    console.log("hello world!");
});



/* PSEUDOCODE
1. submit guess = user's guess
    - begin a timer and display it upon first successful submission
2. return error message for any duplicate numbers in guess
3. lock code is randomly generated by pulling 3 items out of number array, thus no duplicates
4. user guess is compared to lock code
    - for any guesses that are in the correct spot, return correctPlace message
    - for any guesses that are correct but in the wrong spot, return incorrectPlace message
    - for any guesses that are all incorrect, return wrong message
5. display hint message next to each of the results
6. if the complete code isn't guessed correctly, for the following guess, create a new row of results
    below the first row
7. If complete code is guessed correctly, return message of completion and display
    - number of lines it took to complete
    - time it took
8. Allow user to change number of digits to unlock between 2-10 digits
*/